accounts/urls.py
from django.conf.urls import url
from . import views

app_name ='accounts'

urlpatterns = [

    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),


]

posts/urls.py
from django.conf.urls import url
from . import views

app_name ='posts'

urlpatterns = [

    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^author_posts/(?P<fk>[0-9]+)', views.author_posts, name='author_posts'),


]

redditclone/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from posts import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home , name = 'home'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total= models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%d %m %Y')

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout


# Create your views here.
def signup(request):

    if request.method == 'POST':

        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(username = request.POST['username'], password=request.POST['password1'])
            login(request,user)
            return redirect ('home')
        else:
            return render(request, 'accounts/signup.html', {'error':'password do not match'})



    else:
        return render(request, 'accounts/signup.html')




def loginview(request):

    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']


        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect (request.POST['next'])
            else:
                return redirect ('home')
        else:
            return render(request, 'accounts/login.html', {'error':'no such user, please try again'})

    else:
        return render(request, 'accounts/login.html')


def logoutview(request):
    logout(request)
    return redirect ('home')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post

@login_required(login_url='/accounts/login/')

def create(request):

    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']

            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']

            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect ('home')
        else:
            return render(request, 'posts/create.html', {'error':'the title or url is missing'})


    else:
        return render(request, 'posts/create.html')

def home(request):
    post = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'postim':post})


def author_posts(request, fk):
    post = Post.objects.filter(author__id = fk ).order_by('-votes_total')
    the_author = User.objects.get(pk=fk)
    return render(request, 'posts/author_posts.html', {'postim':post, 'the_author':the_author})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect ('home')


def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect ('home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Login</h1>

  {% if error %}
    {{error}}
    {% endif %}

<form method="POST" action="{% url 'accounts:login' %}">
  {% csrf_token %}

  {% if request.GET.next %}
      <input type="hidden" name="next" value={{request.GET.next}} />
  {% endif  %}
     <h2>insert username:</h2>
 <input type="text" name="username" />
 <br>
     <h2>password</h2>
 <input type="password" name="password" /> <br><br>
 <input type="submit" name="submit" value="sign up"/>

</form>

{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}


    <div class="panel panel-default panel-center">
      <div class="panel-heading"><h3>sign up!</h3></div>

      <div class="panel-body">

                <div class="alert alert-danger alert-dismissable" >
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                 {% if error %}
                  {{error}}
                  {% endif %}
              </div>

              <form method="POST" action="{% url 'accounts:signup' %}">
                {% csrf_token %}
                  <h4><span class="glyphicon glyphicon-search"> username</span></h4>
               <input type="text" name="username" />
               <br>
                   <h4><span class="glyphicon glyphicon-search"> password</span></h4>
               <input type="password" name="password1" /> <br>
                   <h4><span class="glyphicon glyphicon-search"> re-password</span></h4>
               <input type="password" name="password2" /> <br><br>
               <input type="submit" class="btn btn-primary" name="submit" value="sign up"/>

              </form>


      </div>


{% endblock%}

posts/templates/posts/author_posts.html
{% extends 'base.html' %}

{% block content %}
<h1>The Posts of {{the_author.username}}</h1>
<br>
<br>

{% for post in postim.all %}


<div class="row">


<!-- this part is the arrows and counts -->
<div class="col-sm-1" align="center">

  <a href="#" onClick="document.getElementById('arrowup{{ post.id }}').submit();"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>

  <form id="arrowup{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" name="click" />
  </form>

  <h4><strong>{{post.votes_total}}</strong></h4>

  <a href="#" onClick="document.getElementById('arrowbottom{{ post.id }}').submit();"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
  <form id="arrowbottom{{post.id}}" method="POST" action=" {% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden"/>
  </form>
</div>

<!-- this part is the arrows and counts -->
<div class="col-sm-4">
  <a href="{{ post.url }}" ><h3>{{post.title}} </h3></a>
  created at: {{post.pub_date_pretty}}, by {{post.author.username}}
  <hr>
</div>
</div>


{% endfor %}


{% endblock%}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

  <h1>Create post</h1>

    {% if error %}
      {{error}}
      {% endif %}

  <form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}

       <h2>insert title:</h2>
   <input type="text" name="title" />
   <br>
       <h2>insert url</h2>
   <input type="text" name="url" /> <br><br>
   <input type="submit" name="submit" value="post"/>

  </form>

{% endblock%}

posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>The front page of nowhere</h1>
<a class="btn btn-primary" href={% url 'posts:create' %} >New Post</a>
<br>
<br>

{% for post in postim.all %}


<div class="row">


<!-- this part is the arrows and counts -->
<div class="col-sm-1" align="center">

  <a href="#" onClick="document.getElementById('arrowup{{ post.id }}').submit();"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>

  <form id="arrowup{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
    {% csrf_token %}
    <input type="hidden" name="click" />
  </form>

  <h4><strong>{{post.votes_total}}</strong></h4>

  <a href="#" onClick="document.getElementById('arrowbottom{{ post.id }}').submit();"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
  <form id="arrowbottom{{post.id}}" method="POST" action=" {% url 'posts:downvote' post.id %}">
    {% csrf_token %}
    <input type="hidden"/>
  </form>
</div>

<!-- this part is the arrows and counts -->
<div class="col-sm-4">
  <a href="{{ post.url }}" ><h3>{{post.title}} </h3></a>
  created at: {{post.pub_date_pretty}}, by <a href="#" onClick="document.getElementById('author{{ post.id }}').submit();">{{post.author.username}}</a>

  <form id="author{{post.id}}" method="POST" action="{% url 'posts:author_posts' post.author.id %}">
    {% csrf_token %}
    <input type="hidden"/>
  </form>


  <hr>
</div>
</div>


{% endfor %}


{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Itamar Blog</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container">
            <!-- the Header -->
                  <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                          </button>
                       <a class="navbar-brand" href="{% url 'home' %}">Reddit clone</a>
                  </div>

                  <div class="collapse navbar-collapse" id="mynav">
                      <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                          <li><a href="{% url 'accounts:logout' %}">{{ user.username }}, sign out</a></li>
                        {% else %}
                          <li><a href="{% url 'accounts:login' %}">login</a></li>
                          <li><a href="{% url 'accounts:signup' %}">register</a></li>
                        {% endif%}
                      </ul>
                  </div>

      </div>
    </nav>

    <div class="container" style="text-align: left;">
      {% block content %}

      {% endblock %}

     </div class="container">

<br />





    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>